# Generated by Django 5.1.3 on 2025-01-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
                ('module_duration', models.IntegerField()),
                ('class_room', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studno', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('modules', models.ManyToManyField(to='app_manytomany.modules')),
            ],
        ),
    ]
