# Generated by Django 5.1.3 on 2025-01-01 15:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileSerials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_name', models.CharField(blank=True, max_length=30, null=True)),
                ('next_serial_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MFOsub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('mfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.mfo')),
            ],
        ),
        migrations.CreateModel(
            name='MFOsub2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('mfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.mfo')),
                ('mfosub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.mfosub')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('task_desc', models.TextField(blank=True, null=True)),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('diff', models.DurationField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doc_img', models.ImageField(blank=True, null=True, upload_to='doc_images/')),
                ('posted_serial', models.CharField(blank=True, max_length=30, null=True)),
                ('is_posted', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_task.taskcategory')),
                ('mfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_task.mfo')),
                ('mfosub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_task.mfosub')),
                ('mfosub2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_task.mfosub2')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('diff', models.DurationField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('revision', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app_task.tasktable')),
            ],
        ),
    ]
