# Generated by Django 5.1.3 on 2024-12-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0002_rename_tasklist_tasktable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktable',
            name='diff',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
