# Generated by Django 5.1.3 on 2024-12-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0003_tasktable_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktable',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktable',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasktable',
            name='posted_serial',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
