# Generated by Django 5.1.3 on 2024-12-04 16:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0005_file_serials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File_Serials',
            new_name='FileSerials',
        ),
    ]
