# Generated by Django 5.1.3 on 2024-12-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0008_taskhistory_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktable',
            name='task_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
