# Generated by Django 5.1.3 on 2024-12-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0012_taskhistory_revision_taskhistory_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='coreFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
