# Generated by Django 5.1.3 on 2024-12-10 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0013_corefunctions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktable',
            name='core',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_task.corefunctions'),
        ),
        migrations.CreateModel(
            name='coreSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('core_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.corefunctions')),
            ],
        ),
    ]
