# Generated by Django 5.1.3 on 2024-12-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0014_tasktable_core_coresection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corefunctions',
            name='core_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
