# Generated by Django 5.1.3 on 2024-12-10 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0015_alter_corefunctions_core_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktable',
            name='core_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_task.coresection'),
        ),
        migrations.AlterField(
            model_name='tasktable',
            name='core',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_task.corefunctions'),
        ),
    ]
