# Generated by Django 5.1.3 on 2024-12-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0016_tasktable_core_section_alter_tasktable_core'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coreFunctions',
            new_name='MFO',
        ),
    ]
