# Generated by Django 5.1.3 on 2024-12-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0017_rename_corefunctions_mfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mfo',
            old_name='core_name',
            new_name='name',
        ),
    ]
