# Generated by Django 5.1.3 on 2024-12-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0019_rename_coresection_mfosub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktable',
            old_name='core',
            new_name='mfo',
        ),
    ]
