# Generated by Django 5.1.3 on 2024-12-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0020_rename_core_tasktable_mfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mfosub',
            old_name='core_name',
            new_name='mfo',
        ),
        migrations.RenameField(
            model_name='tasktable',
            old_name='core_section',
            new_name='mfosub',
        ),
    ]
