# Generated by Django 5.1.3 on 2024-12-13 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0021_rename_core_name_mfosub_mfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFOsub2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('mfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.mfo')),
                ('mfosub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.mfosub')),
            ],
        ),
    ]
