# Generated by Django 5.1.3 on 2024-12-13 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0022_mfosub2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktable',
            name='mfosub2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_task.mfosub2'),
        ),
    ]
