# Generated by Django 5.1.3 on 2024-12-18 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0024_alter_taskhistory_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='reference',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app_task.tasktable'),
        ),
    ]
