# Generated by Django 5.1.3 on 2024-12-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0025_alter_taskhistory_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
