# Generated by Django 5.1.3 on 2025-01-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0003_task_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_todo',
            name='user',
        ),
    ]
