# Generated by Django 5.1.3 on 2025-01-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emp_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('emp_position', models.ManyToManyField(blank=True, null=True, to='app_query.position')),
            ],
        ),
    ]
