# Generated by Django 5.1.3 on 2025-01-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_query', '0002_position_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_position',
            field=models.ManyToManyField(blank=True, to='app_query.position'),
        ),
    ]
