# Generated by Django 5.1.3 on 2024-12-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_query', '0004_author_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='name',
            new_name='store_name',
        ),
    ]
