# Generated by Django 5.1.3 on 2024-12-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_query', '0006_course_teacher_student_classroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='students',
            new_name='student',
        ),
    ]
