# Generated by Django 5.1.3 on 2024-12-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_query', '0007_rename_students_classroom_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studno',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
