# Generated by Django 5.1.3 on 2024-12-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_query', '0008_alter_student_studno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('task_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
