# Generated by Django 5.1.3 on 2024-12-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_query', '0010_alter_task_end_time_alter_task_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
