# Generated by Django 5.1.3 on 2024-12-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccess',
            old_name='article_create',
            new_name='supervisor',
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='article_delete',
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='post_notary_access',
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='programmer_access',
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='todo_access_all',
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='todo_rights',
        ),
    ]
