# Generated by Django 5.1.3 on 2024-12-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_rename_article_create_useraccess_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='post_task',
            field=models.BooleanField(default=False),
        ),
    ]
